### ISSUE TITLE
Windows Disk Optimalisation | Feature | pcHealth

### ISSUE THREAD

**Issue by REALSDEALS** [REALSDEALS/pcHealth#134]
**Is your feature request related to a problem? Please describe.**
Opens a GUI for the user to 'quickly' optimalisate their drive(s). 

**Describe the solution you'd like**
Make it easier for the users to optimalisate their drive, to keep them healthy.

**Describe alternatives you've considered**
None, external program -- DiskMark etc (See menu 2/Tools)

**Additional context**
None.

**Comment by BigoStream** [comment]
Added this function in the script.
