### ISSUE TITLE
Tracer log file | Bugg | pcHealth

### ISSUE THREAD

**Issue by REALSDEALS** [REALSDEALS/pcHealth#151]
**Describe the bug**
Tracer function doesn't open the folder/logfile is the user, uses this option.

**To Reproduce**
1. Open Script (.cmd)
2. Run as admin.
3. Use function 1.
4. Use function 13.
5. Give it a URL.
6. Use function 1, after the script gives you the option.
7. Script crashes; instead of opening a folder/logfile.

**Expected behavior**
Script should open the folder and/or open the logfile.

**Comment by Stensel8** [comment]
Hi,

I changed something on line 374 of your code. Let me know if that works!
